use_frameworks!

platform :ios, '9.0'

target 'xListViewController_Example' do
  pod 'xListViewController', :path => '../'

  target 'xListViewController_Tests' do
    inherit! :search_paths

    
  end
end
